### ISSUE TITLE
LNK2001 Error with Eigen Support in AutoDiff

### ISSUE THREAD

**Issue by George-Eric** [autodiff/autodiff#114]
Hi Allan:

Thank you very much for all your work!

AutoDiff is central to my work (Quantitative Finance) and would value your assistance to resolve my issue.

I use the Eigen C++ library in conjunction with AutoDiff.

The functions that I would like to compute derivatives for are defined in terms of matrix operations for which I use Eigen. However, when I use the AutoDiff types with Eigen I get a LNK2001 error in VS2019.

Example:
autodiff::MatrixXDual m{2,2};
//Fill m with autodiff::dual instances
m.determinant();

The call to compute the determinant causes a LNK2001 error complaining about an unresolved external symbol with the mangled name of the determinant method for the MatrixXDual class.
The LNK2001 error is not specific to the determinant, but also occurs for other functionality like the inverse.

I can see that you have added support for the Eigen matrices at the top of the file  <autodiff/forward/eigen.hpp> and also for the Reverse mode, but are they complete or is the error on my side?

Kind regards,
George-Eric

**Comment by allanleal** [comment]
Hi George, thanks for your feedback and reporting this. 

You need to include `Eigen/LU` in addition to `Eigen/Core` to have `determinant` functionality. The example belows compiles with g++ 7.3.0:

~~~c++
// C++ includes
#include <iostream>
using namespace std;

// Eigen includes
#include <Eigen/LU>
using namespace Eigen;

// autodiff include
#include <autodiff/forward.hpp>
#include <autodiff/forward/eigen.hpp>
using namespace autodiff;

int main()
{
    MatrixXdual m(2, 2);
    m << 1.0, 2.0, 2.0, 1.0;

    std::cout << m.determinant() << std::endl;
}
~~~

and prints `-3`.

I'll close this issue, but let me know if it persists.

**Comment by George-Eric** [comment]
Hi Allan:

Thank you very much for your assistance!

Problem resolved.

Kind regards,
George
