### ISSUE TITLE
Eigen headers include problem

### ISSUE THREAD

**Issue by DashReza7** [autodiff/autodiff#385]
I get into the following error when trying to build with `MSVC 19.42.34438.0` for some files using eigen:

`error C1189: #error:  "Please include Eigen/Core instead of including headers inside the src directory directly."`

I'm using Eigen3 commit: `f5ead2d3`, and autodiff `1.1.2`
